apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend
    type: frontend
spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx:latest
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
  selector:
    matchLabels:
      type: frontend
  replicas: 3
