apiVersion: v1
kind: Service
metadata:
  name: app-html-loadbalance
spec:
  selector:
    app: app-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30001
  type: LoadBalancer
