apiVersion: v1
kind: Pod
metadata:
  name: pod-service
spec:
  containers:
  - name: pod-service
    image: httpd:2.4
    ports:
    - containerPort: 8080

#service

apiVersion: v1
kind: Service
metadata:
  name: service-service
spec:
  type: NodePort
  selector:
    app: pod-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005
