apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: nginx-2
    tier: frontend
spec:
  containers:
    - name: nginx-2
      image: nginx
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
